# Generated by Django 3.2.4 on 2021-07-19 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_auto_20210719_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follows',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='user',
        ),
        migrations.AddField(
            model_name='follow',
            name='followee',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='auth.user'),
            preserve_default=False,
        ),
    ]
