# Generated by Django 3.2.4 on 2021-07-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210721_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='darkmode',
            field=models.BooleanField(default=True),
        ),
    ]
