# Generated by Django 3.2.4 on 2021-07-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_userpreferences_darkmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='My bio!', max_length=280, null=True),
        ),
    ]
