version: '3.4'

services:
    web:
        image: web
        build:
            context: ./
            dockerfile: ./Dockerfile
        command: bash -c "gunicorn mainbase.wsgi -b 0.0.0.0:8001"
        volumes:
            - static_volume:/home/app/static
        expose: 
            - "8001"
    nginx:
        build: ./nginx
        volumes:
            - static_volume:/static
        ports:
        - 8000:8000
        depends_on: 
            - web

volumes:
    static_volume: