# Generated by Django 3.2.4 on 2021-06-08 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_created',
            new_name='date_posted',
        ),
    ]
