# Generated by Django 3.2.4 on 2021-06-12 07:11

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_date_created_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default=blog.models.uuid_hex, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
