# Generated by Django 3.2.4 on 2021-06-12 08:34

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default=blog.models.uuid_hex, max_length=32, primary_key=True, serialize=False),
        ),
    ]
